### PR TITLE
Pass request object to setLastRequestTime/getLastRequestTime

### PR DESCRIPTION
**Pull request by Anyqax**
I need to set/get the last request time based on some information contained in the request... an api-key in my case. This pull request adds the request as a parameter to the associated methods.
Unfortunately that's a BC break, so would require a version bump.

### CODE REVIEW

**Review by localheinz — APPROVED** [review]
👍 Looks good to me, but is a BC-breaking change (which, of course, you already pointed out).

**Comment by rtheunissen** [comment]
Let's do major update then. ✨

**Comment by localheinz** [comment]
@rtheunissen 

While at it, do you see any reason to update PHP requirements?

**Comment by Anyqax** [comment]
anything holding this back?

**Comment by rtheunissen** [comment]
@Anyqax nope, tagged as 2.0 👍

**Pull request merged**
